
mkdir temp_build

cd ./temp_build

cmake ../opencv/ \
-D CMAKE_TOOLCHAIN_FILE=$PWD/../toolchain-arm64.cmake \
-D OPENCV_EXTRA_MODULES_PATH=$PWD/../opencv_contrib/modules/ \
-D CMAKE_INSTALL_PREFIX=$PWD/../build_opencv \
-D CMAKE_POSITION_INDEPENDENT_CODE=ON \
-D WITH_TBB=ON \
-D BUILD_TBB=ON \
-D BUILD_SHARED_LIBS=ON \
-D BUILD_TESTS=OFF \
-D BUILD_PERF_TESTS=OFF \
-D OPENCV_ENABLE_NONFREE=ON \
-D OPENCV_GENERATE_PKGCONFIG=ON \
-D BUILD_opencv_python3=ON \
-D INSTALL_PYTHON_EXAMPLES=OFF \
-D CMAKE_BUILD_TYPE=RELEASE \
-D BUILD_opencv_xphoto=OFF

make -j 32
make install


#  1069  export TOOLCHAIN=${NDK}/build/cmake/android.toolchain.cmake
#  1425  cmake ../../  
# -DCMAKE_POSITION_INDEPENDENT_CODE=ON 
# -DBUILD_SAMPLES=OFF 
# -Dprotobuf_BUILD_TESTS=OFF 
# -DCMAKE_BUILD_TYPE=Release 
# -DCMAKE_SYSTEM_NAME=Linux 
# -DCMAKE_SYSTEM_PROCESSOR=x86_64
#  1426  cmake ../  
# -DCMAKE_POSITION_INDEPENDENT_CODE=ON 
# -DBUILD_SAMPLES=OFF 
# -Dprotobuf_BUILD_TESTS=OFF 
# -DCMAKE_BUILD_TYPE=Release 
# -DCMAKE_SYSTEM_NAME=Linux 
# -DCMAKE_SYSTEM_PROCESSOR=x86_64
#  1435  cmake ../ 
# -D CMAKE_BUILD_TYPE=RELEASE 
# -D CMAKE_INSTALL_PREFIX=/home/khomin/Documents/PROJECTS/YOLO_detector/opencv/build_linux_x86/ 
# -D CMAKE_POSITION_INDEPENDENT_CODE=ON 
# -D WITH_TBB=ON 
# -D BUILD_TBB=ON 
# -D BUILD_SHARED_LIBS=ON 
# -D BUILD_TESTS=OFF 
# -D BUILD_PERF_TESTS=OFF 
# -D OPENCV_ENABLE_NONFREE=ON 
# -D OPENCV_GENERATE_PKGCONFIG=ON 
# -D OPENCV_EXTRA_MODULES_PATH=/home/khomin/Documents/PROJECTS/YOLO_detector/opencv_contrib/modules/ 
# -D BUILD_opencv_python3=ON 
# -D INSTALL_PYTHON_EXAMPLES=OFF
#  1446  cmake ../ 
# -D CMAKE_BUILD_TYPE=RELEASE 
# -D CMAKE_INSTALL_PREFIX=/home/khomin/Documents/PROJECTS/YOLO_detector/opencv/build_linux_x86/ 
# -D CMAKE_POSITION_INDEPENDENT_CODE=ON 
# -D WITH_TBB=ON 
# -D BUILD_TBB=ON 
# -D BUILD_SHARED_LIBS=ON 
# -D BUILD_TESTS=OFF 
# -D BUILD_PERF_TESTS=OFF 
# -D OPENCV_ENABLE_NONFREE=ON 
# -D OPENCV_GENERATE_PKGCONFIG=ON 
# -D OPENCV_EXTRA_MODULES_PATH=/home/khomin/Documents/PROJECTS/YOLO_detector/opencv_contrib/modules/ 
# -D BUILD_opencv_python3=ON 
# -D INSTALL_PYTHON_EXAMPLES=OFF
#  1449  cmake ../ 
# -D CMAKE_BUILD_TYPE=RELEASE 
# -D CMAKE_INSTALL_PREFIX=/home/khomin/Documents/PROJECTS/YOLO_detector/opencv/build_linux_x86/ 
# -D CMAKE_POSITION_INDEPENDENT_CODE=ON 
# -D WITH_TBB=ON 
# -D BUILD_TBB=ON 
# -D BUILD_SHARED_LIBS=ON 
# -D BUILD_TESTS=OFF 
# -D BUILD_PERF_TESTS=OFF 
# -D OPENCV_ENABLE_NONFREE=ON 
# -D OPENCV_GENERATE_PKGCONFIG=ON 
# -D OPENCV_EXTRA_MODULES_PATH=/home/khomin/Documents/PROJECTS/YOLO_detector/opencv_contrib/modules/ 
# -D BUILD_opencv_python3=ON 
# -D INSTALL_PYTHON_EXAMPLES=OFF 
# -DBUILD_EXAMLES=ON
#  1454  cmake ../ 
# -D CMAKE_BUILD_TYPE=RELEASE 
# -D CMAKE_INSTALL_PREFIX=/home/khomin/Documents/PROJECTS/YOLO_detector/opencv/build_linux_x86/ 
# -D CMAKE_POSITION_INDEPENDENT_CODE=ON 
# -D WITH_TBB=ON 
# -D BUILD_TBB=ON 
# -D BUILD_SHARED_LIBS=ON 
# -D BUILD_TESTS=OFF 
# -D BUILD_PERF_TESTS=OFF 
# -D OPENCV_ENABLE_NONFREE=ON 
# -D OPENCV_GENERATE_PKGCONFIG=ON 
# -D OPENCV_EXTRA_MODULES_PATH=/home/khomin/Documents/PROJECTS/YOLO_detector/opencv_contrib/modules/ 
# -D BUILD_opencv_python3=ON 
# -D INSTALL_PYTHON_EXAMPLES=OFF 
# -DBUILD_EXAMLES=ON
#  1461  cmake ../ 
# -D CMAKE_BUILD_TYPE=RELEASE 
# -D CMAKE_INSTALL_PREFIX=/home/khomin/Documents/PROJECTS/YOLO_detector/opencv/build_linux_x86/ 
# -D CMAKE_POSITION_INDEPENDENT_CODE=ON 
# -D WITH_TBB=ON 
# -D BUILD_TBB=ON 
# -D BUILD_SHARED_LIBS=ON 
# -D BUILD_TESTS=OFF 
# -D BUILD_PERF_TESTS=OFF 
# -D OPENCV_ENABLE_NONFREE=ON 
# -D OPENCV_GENERATE_PKGCONFIG=ON 
# -D OPENCV_EXTRA_MODULES_PATH=/home/khomin/Documents/PROJECTS/YOLO_detector/opencv_contrib/modules/ 
# -D BUILD_opencv_python3=ON 
# -D INSTALL_PYTHON_EXAMPLES=OFF
#  1463  cmake ../ 
# -D CMAKE_BUILD_TYPE=RELEASE 
# -D CMAKE_INSTALL_PREFIX=/home/khomin/Documents/PROJECTS/YOLO_detector/opencv/build_linux_x86/ 
# -D CMAKE_POSITION_INDEPENDENT_CODE=ON 
# -D WITH_TBB=ON 
# -D BUILD_TBB=ON 
# -D BUILD_SHARED_LIBS=ON 
# -D BUILD_TESTS=OFF 
# -D BUILD_PERF_TESTS=OFF 
# -D OPENCV_ENABLE_NONFREE=ON 
# -D OPENCV_GENERATE_PKGCONFIG=ON 
# -D OPENCV_EXTRA_MODULES_PATH=/home/khomin/Documents/PROJECTS/YOLO_detector/opencv_contrib/modules/ 
# -D BUILD_opencv_python3=ON 
# -D INSTALL_PYTHON_EXAMPLES=OFF 
# -D BUILD_opencv_xphoto=OFF
#  1466  cmake ../ 
# -D CMAKE_BUILD_TYPE=RELEASE 
# -D CMAKE_INSTALL_PREFIX=/home/khomin/Documents/PROJECTS/YOLO_detector/cpp/build_linux_x86 
# -D CMAKE_POSITION_INDEPENDENT_CODE=ON 
# -D WITH_TBB=ON 
# -D BUILD_TBB=ON 
# -D BUILD_SHARED_LIBS=ON 
# -D BUILD_TESTS=OFF 
# -D BUILD_PERF_TESTS=OFF 
# -D OPENCV_ENABLE_NONFREE=ON 
# -D OPENCV_GENERATE_PKGCONFIG=ON 
# -D OPENCV_EXTRA_MODULES_PATH=/home/khomin/Documents/PROJECTS/YOLO_detector/opencv_contrib/modules/ 
# -D BUILD_opencv_python3=ON 
# -D INSTALL_PYTHON_EXAMPLES=OFF 
# -D BUILD_opencv_xphoto=OFF
